/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemManager;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Hotel.Hotel;
import Business.Enterprise.TravelCompany.TravelCompany;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author quanhaonan
 */
public class Addenterprise extends javax.swing.JPanel {

    /**
     * Creates new form Addenterprise
     */
    private EcoSystem system;
    private JPanel workarea;
    private SystemManagerMainJPanel mng;
    private Network net;
    private List<Enterprise> enlist;
    private String path;
    private TravelCompany tc=new TravelCompany(null,null , null);
    private Hotel h=new Hotel(null, null, null);
    public Addenterprise(EcoSystem system, JPanel workarea, SystemManagerMainJPanel mng, Network net) {
        initComponents();
        this.system=system;
        this.workarea=workarea;
        this.mng=mng;
        this.net=net;
        enlist=net.getEnterpriseDirectory().getEnterpriseList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterprise = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phonetext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addresstext = new javax.swing.JTextField();
        confirmbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        enterprise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel", "TransportCompany" }));

        jLabel1.setText("EnterpriseType:");

        jLabel2.setText("Name:");

        jLabel3.setText("Phone:");

        jLabel4.setText("Address:");

        confirmbtn.setText("confirm");
        confirmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbtnActionPerformed(evt);
            }
        });

        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("UploadPhoto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enterprise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nametext)
                            .addComponent(phonetext)
                            .addComponent(addresstext)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(phonetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(confirmbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbtnActionPerformed
        // TODO add your handling code here:
        String name=nametext.getText();
        String address=addresstext.getText();
        String phone=phonetext.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "name cann't be empty");
            return ;
        }
        if(address.equals("")){
            JOptionPane.showMessageDialog(null, "name cann't be empty");
            return ;
        }
        if(phone.equals("")){
            JOptionPane.showMessageDialog(null, "name cann't be empty");
            return ;
        }
        for(Enterprise e:enlist){
                if(name.equals(e.getName())){
                    JOptionPane.showMessageDialog(null, "This enterprise existed");
                }
            }
        int i=enterprise.getSelectedIndex();
        if(i==0){
            h=new Hotel(name, address, phone);
            h.setAddress(address);
            h.setName(name);
            h.setPhonenumber(phone);
            h.creatOrganization();
//            h=net.createHotel(name, address, phone);
           net.getEnterpriseDirectory().getEnterpriseList().add(h);
        }else if(i==1){
           // tc=new TravelCompany(name, phone, address);
           // tc=net.createTravelCompany(name, address, phone);
            tc.setAddress(address);
            tc.setPhonenumber(phone);
            tc.setName(name);
            tc.creatOrganization();
            net.getEnterpriseDirectory().getEnterpriseList().add(tc);
        }
        DB4OUtil.getInstance().storeSystem(system);
        workarea.remove(this);
        mng.populateenterprise();
        mng.populateTree();
        CardLayout layout=(CardLayout)workarea.getLayout();
        layout.previous(workarea);
    }//GEN-LAST:event_confirmbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        //mng.populatenetwork();
        CardLayout layout=(CardLayout)workarea.getLayout();
        layout.previous(workarea);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int i = chooser.showOpenDialog(null);
        if (i == chooser.APPROVE_OPTION) {
            path = chooser.getSelectedFile().getAbsolutePath();
            int j=enterprise.getSelectedIndex();
        if(j==0){
            h.setPhotoPath(path);
        }else if(j==1){
            tc.setPhotoPath(path);
        }
        } else {
            JOptionPane.showMessageDialog(null, "You didn't choose a photo");
        }
//        ImageIcon image = new ImageIcon(path);
//        image.setImage(image.getImage().getScaledInstance(250, 180, Image.SCALE_DEFAULT));
        //imageLabel.setIcon(image);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstext;
    private javax.swing.JButton confirmbtn;
    private javax.swing.JComboBox<String> enterprise;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nametext;
    private javax.swing.JTextField phonetext;
    // End of variables declaration//GEN-END:variables
}
