/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemManager;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author quanhaonan
 */
public class Addnetwork extends javax.swing.JPanel {

    /**
     * Creates new form Addnetwork
     */
    private EcoSystem system;
    private JPanel workarea;
    private SystemManagerMainJPanel mng;
    public Addnetwork(EcoSystem system, JPanel workarea, SystemManagerMainJPanel mng) {
                initComponents();
                this.system=system;
                this.workarea=workarea;
                this.mng=mng;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        confirmbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();

        jLabel1.setText("Name:");

        nametext.setText(" ");

        confirmbtn.setText("Confirm");
        confirmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbtnActionPerformed(evt);
            }
        });

        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmbtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelbtn)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmbtn)
                    .addComponent(cancelbtn))
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbtnActionPerformed
        // TODO add your handling code here:
        String city=nametext.getText();
        if(city.equals("")){
            JOptionPane.showMessageDialog(null,"city name can not be null");
            return ;
        }else{
            if(system.isCityAvabliable(city)){
            
            }else {
                JOptionPane.showMessageDialog(null,"city has already exisit");
                return ;
            }
        }
        
        Network net=new Network(nametext.getText());
        system.getNetworkList().add(net);
        DB4OUtil.getInstance().storeSystem(system);

//        Component[]comps=workarea.getComponents();
//            for(Component comp:comps){
//            if(comp instanceof MngCar){
//                MngCar manageP=(MngCar) comp;
//                manageP.populate();
//            }
//        }
        JOptionPane.showMessageDialog(null,"network create successfully");
       
        workarea.remove(this);
        mng.populatenetwork();
        CardLayout layout=(CardLayout)workarea.getLayout();
        layout.previous(workarea);
    }//GEN-LAST:event_confirmbtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        CardLayout layout=(CardLayout)workarea.getLayout();
        layout.previous(workarea);
    }//GEN-LAST:event_cancelbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JButton confirmbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nametext;
    // End of variables declaration//GEN-END:variables
}
