/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;


import Business.Customer.HotelOrder;
import Business.Customer.ItemOrder;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Hotel.Hotel;
import Business.Enterprise.Hotel.Room;
import Business.Enterprise.Item;
import Business.Enterprise.Model;
import Business.Enterprise.Model.EnterpriseType;
import Business.Network.Network;
import Business.UserAccount.CustomerAccount;
import Business.WorkQueue.OrderRequest;
import Business.WorkQueue.ReviewRequest;
import Business.WorkQueue.TransportRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roc
 */
public class HotelDetailsJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private Hotel model;
    private CustomerAccount account;
    private Network net;
    private EnterpriseType type;

    /**
     * Creates new form HotelDetailsJPanel
     */
    public HotelDetailsJPanel(EcoSystem system, Hotel hotel, CustomerAccount account, Network net, EnterpriseType type) {
        initComponents();
        this.system = system;
        this.model = hotel;
        this.account = account;
        this.net = net;
        this.type = type;

//        if (!type.equals(EnterpriseType.Hotel)) {
//            this.jTabbedPane1.setTitleAt(1, "Product");
//        }

        showImage();
        
       
        if (model.getRate(net.getWorkqueue())== -1) {
            ratelabel.setText("N/A");
        } else {
            ratelabel.setText(model.getRate(net.getWorkqueue()) + "");
        }
        addressTextArea1.setText(model.getAddress());
        addressTextArea1.setEnabled(false);
//        descriptionTextArea.setText(model.getDescription());
//        descriptionTextArea.setEnabled(false);
        phoneLabel1.setText(model.getPhonenumber());

        // Review tab
        
    }

    

    
    private void showImage() {
        ImageIcon image = null;
        type = type.Hotel;
        if (type.equals(EnterpriseType.Hotel)) {
            Hotel res = (Hotel) model;
            image = new ImageIcon(res.getPhotopath());
        }
//        if (type.equals(EnterpriseType.Hotel)) {
//            Hotel store = (Hotel) model;
//            image = new ImageIcon(store.getPath());
//        }
        image.setImage(image.getImage().getScaledInstance(250, 180, Image.SCALE_DEFAULT));
        imageLabel1.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        addressTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        ratelabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imageLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        phoneLabel1 = new javax.swing.JLabel();

        addressTextArea1.setBackground(new java.awt.Color(238, 238, 238));
        addressTextArea1.setColumns(20);
        addressTextArea1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        addressTextArea1.setLineWrap(true);
        addressTextArea1.setBorder(null);
        addressTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(addressTextArea1);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Phone:");

        ratelabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ratelabel.setText("N/A");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Address: ");

        imageLabel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Rate:");

        phoneLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        phoneLabel1.setText("<Phone>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)
                                .addGap(67, 67, 67))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneLabel1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(ratelabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(phoneLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ratelabel))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTextArea1;
    private javax.swing.JLabel imageLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel phoneLabel1;
    private javax.swing.JLabel ratelabel;
    // End of variables declaration//GEN-END:variables
}
